old_sound_rabbit_mq:
    connections:
        default:
            host: 'rabbit'
            port: 5672
            user: 'guest'
            password: 'guest'
            vhost: '/'
    producers:
        rates_history:
            connection: default
            exchange_options: {name: 'rates_history_exchange', type: 'direct'}
    consumers:
        rates_history:
            connection: default
            exchange_options: {name: 'rates_history_exchange', type: 'direct'}
            queue_options: {name: 'rates_history_queue'}
            callback: 'rates_history_consumer_service'
