version: '3'

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    networks:
      - default
  nginx:
    image: nginx:1.27
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - default
  redis:
    image: redis:7
    networks:
      - default
    expose:
      - 6379
  rabbit:
    image: rabbitmq:3-management
    networks:
      - default
    expose:
      - 5672
    ports:
      - "15672:15672"
networks:
  default: